### ISSUE TITLE
True/False Arguments in Arguments

### ISSUE THREAD

**Issue by sktusing** [sammysmallman/OSCKit#18]
Is it intentional that oscTrue and oscFalse are not included in OSCMessage.arguments?

Received:
`/eos/out/get/cue/1/1/0/list/0/31`
`[-1, "DC049B75-6460-4295-9A02-BA1F48E9BB89", "Cue 1/1", 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, "0", 100, "", "", "", 0, -1, -1, -1, "", 0, "", "", -1]`

Expected:
`/eos/out/get/cue/1/1/0/list/0/31`
`[-1, "DC049B75-6460-4295-9A02-BA1F48E9BB89", "Cue 1/1", 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, False, "0", 100, "", "", "", 0, -1, -1, False, -1, False, "", 0, "", "", False, -1]`

In this example there should be 31 arguments total: there are 31 arguments listed in OSCMessage.argumentTypes, however there are 27 in OSCMessage.arguments.

**Comment by sammysmallman** [comment]
This is something thats bothered me for a while because as you have found arguments and the type tag string get out of alignment. Most OSC libraries do as OSCKit does as technically speaking the true and false argument types don't actually send any argument data, they're just a char in the type tag string to say that they're there.

I'm undecided as to the approach. There is an argument that you shouldn't necessarily be iterating over the arguments, but iterating over the type string characters, this gives you type safety. You then though have to take into account the offset in index, which is annoying...

Like so:
`    
func take(message: OSCMessage) {
        var offset = 0
        // Remember to drop the first character as that is ","
        for (index, type) in message.typeTagString.dropFirst().enumerated() {
            switch type {
            case "i": print("Integer: \(message.arguments[index - offset])")
            case "s": print("String: \(message.arguments[index - offset])")
            case "f": print("Float: \(message.arguments[index - offset])")
            case "b": print("Blob: \(message.arguments[index - offset])")
            case "t": print("Timetag: \(message.arguments[index - offset])")
            case "F":
                offset += 1
                print("False: \(message.arguments[index - offset])")
            case "T":
                offset += 1
                print("True: \(message.arguments[index - offset])")
            case "N":
                offset += 1
                print("Nil: \(message.arguments[index - offset])")
            case "I":
                offset += 1
                print("Impulse: \(message.arguments[index - offset])")
            default: fatalError("Unknown Type! \(type)")
            }
        }
    }
`

But in terms of the API design I feel like I should add the OSCTrue, OSCFalse, OSCNil and OSCImpulse objects into the arguments array, which would reflect how you send those types of arguments...

**Comment by sammysmallman** [comment]
Or iterate over the argument types in a similar fashion to the typeTagString method above...

**Comment by sammysmallman** [comment]
Fixed in v2.0.0

**Comment by sktusing** [comment]
V2.0 does everything I need. Thanks!
